Repository Activiti/activiti-cloud-acceptance-scenarios, pull requests merged in 2020-01, with the labels that each got.

#764 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#765 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#766 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#767 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#768 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#769 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#770 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#771 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#772 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#750 feat(AAE-896): Added Cloud Native Message Events acceptance scenario
  runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceMessages.java
  runtime-acceptance-tests/src/main/resources/stories/runtime-bundle/process-instance-message-actions.story
Labels: do-not-merge, enhancement, ready-for-review

#774 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#775 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#776 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#778 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#780 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#781 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#782 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#783 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#784 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#785 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#787 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#788 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#789 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#790 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#791 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#792 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#793 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#794 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#798 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#799 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#800 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#801 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#803 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#804 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#805 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#806 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#807 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#808 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#809 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#810 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#811 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#812 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#813 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#814 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#815 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#816 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#817 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#796 Update Spring Boot 2.1.12.RELEASE and Spring Cloud Greenwich.SR4 #3047
  .editorconfig
  .travis.yml
  pom.xml
  runtime-acceptance-tests/pom.xml
  runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/helpers/ProcessDefinitionRegistry.java
  runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/helpers/VariableGenerator.java
Labels: do-not-merge

#818 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#819 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#821 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#822 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#823 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#824 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#825 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#826 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#827 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#828 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#829 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#830 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#831 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#832 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#833 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#834 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#835 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#836 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#839 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#840 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#841 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#842 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#843 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#844 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#845 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#846 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#847 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#848 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#849 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#850 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#852 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#854 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#855 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#856 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#857 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#858 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#859 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#860 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#861 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#862 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#863 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#864 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot

#865 fix(versions): update Activiti/activiti-cloud-acceptance-scenarios versions into master
  pom.xml
Labels: updatebot
